export const work = [
    {
        title: 'Michael Legemah',
        description: 'I rebuilt my portfolio website. I came up with the design, did the wireframes, did the user stories, and code',
        image: '/static/mlegTech.gif',
        alt: 'Michael Legemah portfolio website',
        tech: ['React', 'NextJS', 'Tailwind'],
        code: 'https://github.com/MikeLegemah5799/mleg-portfolio',
        hasCode: 'View Code',
        codeDisabled: false,
        link: 'https://mleg.tech/',
        hasLink: 'View Site',
        linkDisabled: false
    },
    {
        title: 'First And Pen',
        description: 'I worked with the CEO on building the site, designing the site, and ad campaigns. Worked on the CMS in the WordPress.',
        image: '/static/firstandPen.gif',
        alt: 'First and Pen website',
        tech: ['WordPress', 'HTML', 'PHP', 'MySQL', 'JavaScript', 'SASS'],
        code: '',
        hasCode: 'Code is Private',
        codeDisabled: true,
        link: 'https://firstandpen.com/',
        hasLink: 'View Site',
        linkDisabled: false
    },
    {
        title: 'OMNY',
        description: 'I worked with a team on the Server Side Rendering React Components. Worked on the CMS in the Laravel framework.',
        image: '/static/omny.gif',
        alt: 'OMNY website',
        tech: ['React', 'Laravel', 'PHP', 'GraphQL', 'MySQL', 'JavaScript', 'SASS'],
        code: '',
        hasCode: 'Code is Private',
        codeDisabled: true,
        link: 'https://omny.info/',
        hasLink: 'View Site',
        linkDisabled: false
    },
    {
        title: 'Northrop Grumman',
        description: 'Led the team that was tasked with creating customizable components and sections as Wordpress Gutenberg blocks.',
        image: '/static/ng.gif',
        alt: 'Northrop Grumman website',
        tech: ['WordPress', 'PHP', 'React', 'Bootstrap', 'MySQL'],
        code: '',
        hasCode: 'Code is Private',
        codeDisabled: true,
        link: 'https://www.northropgrumman.com/',
        hasLink: 'View Site',
        linkDisabled: false
    },
    {
        title: 'Bronzeville Lakefront',
        description: 'I partnered with an agency called Theo & Lotte to do the full stack development on this site. Leveraged WordPress as a CMS.',
        image: '/static/bronzevillelakefront.gif',
        alt: 'Bronzeville Lakefront website',
        tech: ['WordPress', 'PHP', 'Javascript', 'Foundation', 'MySQL'],
        code: '',
        hasCode: 'Code is Private',
        codeDisabled: true,
        link: 'https://bronzevillelakefront.com/',
        hasLink: 'View Site',
        linkDisabled: false
    },
    {
        title: 'MINI USA',
        description: 'I worked with a team to build and update UI components using Angular. Leveraged Adobe Experience Manager(AEM) as a CMS.',
        image: '/static/mini.gif',
        alt: 'MINI USA website',
        tech: ['AEM', 'Angular', 'Javascript', 'CSS', 'Oracle'],
        code: '',
        hasCode: 'Code is Private',
        codeDisabled: true,
        link: 'https://www.miniusa.com/',
        hasLink: 'View Site',
        linkDisabled: false
    },
    {
        title: 'American Kennel Club',
        description: 'I worked with a team to build and redesign the website. Leveraged WordPress as a CMS.',
        image: '/static/akc.gif',
        alt: 'AKC website',
        tech: ['WordPress', 'Pantheon', 'Javascript', 'SASS', 'MySQL'],
        code: '',
        hasCode: 'Code is Private',
        codeDisabled: true,
        link: 'https://www.akc.org/',
        hasLink: 'View Site',
        linkDisabled: false
    },
    {
        title: 'Flexatron TV',
        description: 'I worked with a team to build and redesign the website. Leveraged Shoipify as a CMS and E-Commerce Solution.',
        image: '/static/flexatrontv.gif',
        alt: 'Felxatron TV website',
        tech: ['Shopify', 'JW Player', 'Javascript', 'SASS', 'Liquid'],
        code: '',
        hasCode: 'Code is Private',
        codeDisabled: true,
        link: 'https://flexatron.tv/',
        hasLink: 'View Site',
        linkDisabled: false
    },
    {
        title: 'Mayo Clinic',
        description: 'I worked with a team to build UI components using Angular and Vue. Created pattern library using Storybook.',
        image: '/static/mayoClinic.gif',
        alt: 'Mayo Clinic website',
        tech: ['Angular', 'Vue', 'Javascript', 'SASS', 'Storybook'],
        code: '',
        hasCode: 'Code is Private',
        codeDisabled: true,
        link: 'https://www.mayoclinic.org/',
        hasLink: 'View Site',
        linkDisabled: false
    },
    {
        title: 'The Shadow League',
        description: 'I worked with the CEO on building the site, redesigning the site,ad campaigns, and deployments in AWS. Worked on the CMS in the WordPress.',
        image: '/static/shadowLeague.gif',
        alt: 'The Shadow League website',
        tech: ['WordPress', 'HTML', 'PHP', 'MySQL', 'JavaScript', 'AWS'],
        code: '',
        hasCode: 'Code is Private',
        codeDisabled: true,
        link: 'https://theshadowleague.com/',
        hasLink: 'View Site',
        linkDisabled: false
    },
    {
        title: 'JP Morgan Chase & Co.',
        description: 'I worked with a team to build and update UI components using ES6 Javascript and SASS. Leveraged Adobe Experience Manager(AEM) as a CMS.',
        image: '/static/jpmc.gif',
        alt: 'JP Morgan Chase website',
        tech: ['AEM', 'Javascript', 'SASS'],
        code: '',
        hasCode: 'Code is Private',
        codeDisabled: true,
        link: 'https://www.jpmorganchase.com/',
        hasLink: 'View Site',
        linkDisabled: false
    },
    {
        title: 'Juvenile Diabetes Research Foundation',
        description: 'Worked with a team that was tasked with creating the website in WordPress CMS.',
        image: '/static/jdrf.gif',
        alt: 'Juvenile Diabetes Research Foundation website',
        tech: ['WordPress', 'PHP', 'jQuery', 'Bootstrap', 'MySQL'],
        code: '',
        hasCode: 'Code is Private',
        codeDisabled: true,
        link: 'https://www.jdrf.org/',
        hasLink: 'View Site',
        linkDisabled: false
    }
];